name: Deploy to Server

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts
          ssh-keygen -l -f ~/.ssh/id_ed25519

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          key_path: ~/.ssh/id_ed25519
          port: 22
          script: |
            cd /var/www/app 

            echo "Create .env file" 
            cat > .env <<EOF 
            REDIS_HOST=${{ secrets.REDIS_HOST }}
            REDIS_PORT=${{ secrets.REDIS_PORT }}
            REDIS_USER=${{ secrets.REDIS_USER }}
            REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}
            NODE_ENV=production 
            EOF

            echo "Pull latest code" 
            git pull origin master 

            echo "Rebuild containers"  
            docker compose up -d --build 

            echo "Cleanup" 
            docker image prune -f
